services:
  truelayer2firefly:
    image: passy05/truelayer2firefly:dev
    container_name: truelayer2firefly
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/home/appuser/app/data
    environment:
      - CONFIG_FILE_PATH=/home/appuser/app/data/config.json
    restart: unless-stopped
